openapi: 3.0.3
info:
  title: Transport barcode API
  description: API documentation for the Transport Barcode system
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
tags:
  - name: version
    description: Application version management
  - name: barcodes
    description: Barcode management


paths:
  /api/version:
    get:
      summary: Get Application Version
      description: Retrieve the current version of the application.
      operationId: getVersion
      responses:
        '200':
          description: Application version retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: "1.0.0"
  /barcodes/generateUnique:
    post:
      tags:
        - barcodes  
      summary: Generate a unique barcode image based on the provided data.
      description: Accepts barcode data in the request body and generates a barcode image in PNG format.
      operationId: generateUniqueBarcode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                barcodeData:
                  type: string
                  description: The data that will be encoded into the barcode.
                  example: "ABC123456"
                name:
                  type: string
                  description: An optional name or identifier for the barcode.
                  example: "Product1"
      responses:
        '200':
          description: Successfully generated a unique barcode image.
          content:
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request - Barcode data is required.
        '500':
          description: Internal server error.
  /barcodes/save:
    post:
      tags:
        - Barcodes
      summary: Save barcode metadata and image
      description: Endpoint to save barcode metadata and the image
      operationId: saveBarcode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                metadata:
                  type: object
                  description: JSON object containing the barcode metadata
                image:
                  type: string
                  format: byte
                  description: Base64-encoded image data
      responses:
        '200':
          description: Successfully saved the barcode
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /barcodes/find/{name}:
    get:
      tags:
        - Barcodes
      summary: Find a barcode by its name
      description: Endpoint to find a barcode by its name
      operationId: findBarcodeByName
      parameters:
        - name: name
          in: path
          required: true
          description: The name of the barcode to find
          schema:
            type: string
      responses:
        '200':
          description: Successfully found the barcode
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BarcodeMetaDataResponse'
        '404':
          description: Barcode not found
        '500':
          description: Internal server error

  /barcodes/delete/{name}:
    delete:
      tags:
        - Barcodes
      summary: Delete a barcode by its name
      description: Endpoint to delete a barcode by its name
      operationId: deleteBarcodeByName
      parameters:
        - name: name
          in: path
          required: true
          description: The name of the barcode to delete
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted the barcode
        '404':
          description: Barcode not found
        '500':
          description: Internal server error

components:
  schemas:
    BarcodeMetaDataResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        metadata:
          type: object
          description: Metadata associated with the barcode
        image:
          type: string
          format: byte
          description: Base64-encoded image data for the barcode
